/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.6.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QComboBox *port_comboBox;
    QLabel *SettingLabel;
    QLabel *COMPORT_label;
    QLabel *Title_label;
    QPushButton *Enable_pushButton;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QFrame *line_5;
    QFrame *line_6;
    QLabel *CurrentLabel;
    QLineEdit *Current_lineEdit;
    QPushButton *Current_run_pushButton;
    QLabel *Current_limitlabel;
    QFrame *line_8;
    QLabel *ChannelLabel;
    QFrame *line_7;
    QFrame *line_9;
    QFrame *line_10;
    QFrame *line_11;
    QFrame *line_12;
    QLabel *CurrentLabel_2;
    QLineEdit *List_current_lineEdit;
    QLineEdit *List_time_lineEdit;
    QLabel *Current_limitlabel_2;
    QLabel *Current_limitlabel_3;
    QLabel *Current_limitlabel_4;
    QLabel *Current_limitlabel_5;
    QPushButton *List_add_pushButton;
    QLabel *Current_limitlabel_6;
    QLabel *Current_limitlabel_7;
    QPushButton *List_clear_pushButton;
    QPushButton *List_run_pushButton;
    QPushButton *List_graph_pushButton;
    QPushButton *List_csv_pushButton;
    QFrame *line_13;
    QFrame *line_14;
    QFrame *line_15;
    QFrame *line_16;
    QFrame *line_17;
    QFrame *line_18;
    QFrame *line_19;
    QLabel *CurrentLabel_3;
    QFrame *line_20;
    QLabel *Current_limitlabel_8;
    QLineEdit *SW_frequency_lineEdit;
    QLabel *Current_limitlabel_9;
    QLineEdit *SW_amplitude_lineEdit;
    QLabel *Current_limitlabel_10;
    QLabel *Current_limitlabel_11;
    QLineEdit *SW_offset_lineEdit;
    QLabel *Current_limitlabel_12;
    QLabel *Current_limitlabel_13;
    QPushButton *SW_run_pushButton;
    QFrame *line_21;
    QFrame *line_22;
    QLabel *Current_limitlabel_15;
    QFrame *line_23;
    QLineEdit *R_current_lineEdit;
    QPushButton *R_RUN_pushButton;
    QFrame *line_24;
    QFrame *line_25;
    QFrame *line_26;
    QLabel *CurrentLabel_4;
    QFrame *line_27;
    QLabel *ChannelLabel_2;
    QLineEdit *SW_frequency_lineEdit_2;
    QFrame *line_28;
    QPushButton *Current_run_pushButton_2;
    QLabel *CurrentLabel_5;
    QFrame *line_29;
    QFrame *line_30;
    QLabel *Current_limitlabel_14;
    QFrame *line_31;
    QPushButton *List_csv_pushButton_2;
    QFrame *line_32;
    QLabel *Current_limitlabel_16;
    QPushButton *List_run_pushButton_2;
    QLineEdit *List_current_lineEdit_2;
    QLabel *CurrentLabel_6;
    QLabel *Current_limitlabel_17;
    QLabel *Current_limitlabel_18;
    QLineEdit *SW_offset_lineEdit_2;
    QLabel *Current_limitlabel_19;
    QFrame *line_36;
    QPushButton *List_add_pushButton_2;
    QLabel *Current_limitlabel_20;
    QFrame *line_37;
    QPushButton *List_graph_pushButton_2;
    QLabel *Current_limitlabel_21;
    QFrame *line_39;
    QFrame *line_40;
    QLineEdit *List_time_lineEdit_2;
    QLabel *Current_limitlabel_22;
    QPushButton *SW_run_pushButton_2;
    QLabel *CurrentLabel_8;
    QLabel *Current_limitlabel_23;
    QFrame *line_41;
    QPushButton *List_clear_pushButton_2;
    QLabel *Current_limitlabel_24;
    QLabel *Current_limitlabel_25;
    QLineEdit *SW_amplitude_lineEdit_2;
    QLineEdit *Current_lineEdit_2;
    QFrame *line_42;
    QFrame *line_43;
    QFrame *line_44;
    QLabel *Current_limitlabel_27;
    QFrame *line_46;
    QFrame *line_47;
    QLabel *Current_limitlabel_28;
    QPushButton *refresh_pushButton;
    QLabel *Current_limitlabel_29;
    QLabel *Current_limitlabel_30;
    QLabel *Current_limitlabel_31;
    QLabel *Current_limitlabel_32;
    QPushButton *pushButton;
    QPushButton *Current_stop_pushButton;
    QPushButton *Current_stop_pushButton_2;
    QLabel *label;
    QLabel *label_2;
    QLabel *Title_label_2;
    QLabel *Title_label_3;
    QLabel *label_3;
    QPushButton *List_save_graph_pushButton;
    QLineEdit *R_time_lineEdit;
    QLabel *Current_limitlabel_33;
    QLabel *Current_limitlabel_34;
    QLabel *Current_limitlabel_35;
    QPushButton *R_csv_pushButton;
    QPushButton *R_clear_pushButton;
    QPushButton *R_save_graph_pushButton;
    QPushButton *R_graph_pushButton;
    QPushButton *R_add_pushButton;
    QFrame *line_34;
    QFrame *line_35;
    QPushButton *R_graph_pushButton_2;
    QLabel *CurrentLabel_7;
    QPushButton *R_add_pushButton_2;
    QPushButton *R_RUN_pushButton_2;
    QLabel *Current_limitlabel_36;
    QLabel *Current_limitlabel_37;
    QFrame *line_38;
    QPushButton *R_clear_pushButton_2;
    QPushButton *R_csv_pushButton_2;
    QLineEdit *R_time_lineEdit_2;
    QFrame *line_48;
    QLineEdit *R_current_lineEdit_2;
    QFrame *line_49;
    QLabel *Current_limitlabel_38;
    QLabel *Current_limitlabel_26;
    QPushButton *R_save_graph_pushButton_2;
    QPushButton *List_save_graph_pushButton_2;
    QLabel *Current_limitlabel_39;
    QLabel *Current_limitlabel_40;
    QCheckBox *checkBox_L1;
    QCheckBox *checkBox_SW1;
    QCheckBox *checkBox_R1;
    QCheckBox *checkBox_L2;
    QCheckBox *checkBox_SW2;
    QCheckBox *checkBox_R2;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(738, 831);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        port_comboBox = new QComboBox(centralWidget);
        port_comboBox->setObjectName(QStringLiteral("port_comboBox"));
        port_comboBox->setGeometry(QRect(480, 50, 91, 22));
        SettingLabel = new QLabel(centralWidget);
        SettingLabel->setObjectName(QStringLiteral("SettingLabel"));
        SettingLabel->setGeometry(QRect(550, 0, 101, 21));
        QFont font;
        font.setFamily(QStringLiteral("Garamond"));
        font.setPointSize(11);
        font.setBold(true);
        font.setWeight(75);
        SettingLabel->setFont(font);
        COMPORT_label = new QLabel(centralWidget);
        COMPORT_label->setObjectName(QStringLiteral("COMPORT_label"));
        COMPORT_label->setGeometry(QRect(480, 30, 71, 16));
        Title_label = new QLabel(centralWidget);
        Title_label->setObjectName(QStringLiteral("Title_label"));
        Title_label->setGeometry(QRect(10, 0, 101, 31));
        QFont font1;
        font1.setFamily(QStringLiteral("Garamond"));
        font1.setPointSize(14);
        Title_label->setFont(font1);
        Enable_pushButton = new QPushButton(centralWidget);
        Enable_pushButton->setObjectName(QStringLiteral("Enable_pushButton"));
        Enable_pushButton->setGeometry(QRect(620, 50, 81, 21));
        QFont font2;
        font2.setPointSize(10);
        Enable_pushButton->setFont(font2);
        line = new QFrame(centralWidget);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(532, 80, 188, 20));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(centralWidget);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(710, 10, 20, 80));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(centralWidget);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(460, 8, 20, 81));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(centralWidget);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(640, 0, 80, 20));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(centralWidget);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(470, 0, 78, 20));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(centralWidget);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(0, 80, 721, 21));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        CurrentLabel = new QLabel(centralWidget);
        CurrentLabel->setObjectName(QStringLiteral("CurrentLabel"));
        CurrentLabel->setGeometry(QRect(30, 140, 121, 21));
        CurrentLabel->setFont(font);
        Current_lineEdit = new QLineEdit(centralWidget);
        Current_lineEdit->setObjectName(QStringLiteral("Current_lineEdit"));
        Current_lineEdit->setGeometry(QRect(20, 170, 115, 30));
        Current_run_pushButton = new QPushButton(centralWidget);
        Current_run_pushButton->setObjectName(QStringLiteral("Current_run_pushButton"));
        Current_run_pushButton->setGeometry(QRect(170, 170, 51, 31));
        QFont font3;
        font3.setBold(true);
        font3.setWeight(75);
        Current_run_pushButton->setFont(font3);
        Current_limitlabel = new QLabel(centralWidget);
        Current_limitlabel->setObjectName(QStringLiteral("Current_limitlabel"));
        Current_limitlabel->setGeometry(QRect(40, 200, 71, 16));
        line_8 = new QFrame(centralWidget);
        line_8->setObjectName(QStringLiteral("line_8"));
        line_8->setGeometry(QRect(355, 90, 20, 691));
        line_8->setFrameShape(QFrame::VLine);
        line_8->setFrameShadow(QFrame::Sunken);
        ChannelLabel = new QLabel(centralWidget);
        ChannelLabel->setObjectName(QStringLiteral("ChannelLabel"));
        ChannelLabel->setGeometry(QRect(110, 100, 151, 31));
        QFont font4;
        font4.setFamily(QStringLiteral("Garamond"));
        font4.setPointSize(14);
        font4.setBold(true);
        font4.setWeight(75);
        ChannelLabel->setFont(font4);
        line_7 = new QFrame(centralWidget);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(10, 230, 340, 20));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(centralWidget);
        line_9->setObjectName(QStringLiteral("line_9"));
        line_9->setGeometry(QRect(150, 145, 201, 16));
        line_9->setFrameShape(QFrame::HLine);
        line_9->setFrameShadow(QFrame::Sunken);
        line_10 = new QFrame(centralWidget);
        line_10->setObjectName(QStringLiteral("line_10"));
        line_10->setGeometry(QRect(0, 153, 20, 86));
        line_10->setFrameShape(QFrame::VLine);
        line_10->setFrameShadow(QFrame::Sunken);
        line_11 = new QFrame(centralWidget);
        line_11->setObjectName(QStringLiteral("line_11"));
        line_11->setGeometry(QRect(10, 145, 21, 16));
        line_11->setFrameShape(QFrame::HLine);
        line_11->setFrameShadow(QFrame::Sunken);
        line_12 = new QFrame(centralWidget);
        line_12->setObjectName(QStringLiteral("line_12"));
        line_12->setGeometry(QRect(340, 153, 20, 86));
        line_12->setFrameShape(QFrame::VLine);
        line_12->setFrameShadow(QFrame::Sunken);
        CurrentLabel_2 = new QLabel(centralWidget);
        CurrentLabel_2->setObjectName(QStringLiteral("CurrentLabel_2"));
        CurrentLabel_2->setGeometry(QRect(40, 250, 121, 21));
        CurrentLabel_2->setFont(font);
        List_current_lineEdit = new QLineEdit(centralWidget);
        List_current_lineEdit->setObjectName(QStringLiteral("List_current_lineEdit"));
        List_current_lineEdit->setGeometry(QRect(20, 300, 115, 30));
        List_time_lineEdit = new QLineEdit(centralWidget);
        List_time_lineEdit->setObjectName(QStringLiteral("List_time_lineEdit"));
        List_time_lineEdit->setGeometry(QRect(160, 300, 115, 30));
        Current_limitlabel_2 = new QLabel(centralWidget);
        Current_limitlabel_2->setObjectName(QStringLiteral("Current_limitlabel_2"));
        Current_limitlabel_2->setGeometry(QRect(40, 330, 71, 16));
        Current_limitlabel_3 = new QLabel(centralWidget);
        Current_limitlabel_3->setObjectName(QStringLiteral("Current_limitlabel_3"));
        Current_limitlabel_3->setGeometry(QRect(280, 305, 31, 21));
        Current_limitlabel_3->setFont(font2);
        Current_limitlabel_4 = new QLabel(centralWidget);
        Current_limitlabel_4->setObjectName(QStringLiteral("Current_limitlabel_4"));
        Current_limitlabel_4->setGeometry(QRect(141, 175, 21, 16));
        Current_limitlabel_4->setFont(font2);
        Current_limitlabel_5 = new QLabel(centralWidget);
        Current_limitlabel_5->setObjectName(QStringLiteral("Current_limitlabel_5"));
        Current_limitlabel_5->setGeometry(QRect(141, 305, 21, 16));
        Current_limitlabel_5->setFont(font2);
        List_add_pushButton = new QPushButton(centralWidget);
        List_add_pushButton->setObjectName(QStringLiteral("List_add_pushButton"));
        List_add_pushButton->setGeometry(QRect(310, 300, 31, 31));
        Current_limitlabel_6 = new QLabel(centralWidget);
        Current_limitlabel_6->setObjectName(QStringLiteral("Current_limitlabel_6"));
        Current_limitlabel_6->setGeometry(QRect(50, 280, 61, 16));
        Current_limitlabel_7 = new QLabel(centralWidget);
        Current_limitlabel_7->setObjectName(QStringLiteral("Current_limitlabel_7"));
        Current_limitlabel_7->setGeometry(QRect(200, 280, 61, 16));
        List_clear_pushButton = new QPushButton(centralWidget);
        List_clear_pushButton->setObjectName(QStringLiteral("List_clear_pushButton"));
        List_clear_pushButton->setGeometry(QRect(130, 350, 91, 31));
        List_run_pushButton = new QPushButton(centralWidget);
        List_run_pushButton->setObjectName(QStringLiteral("List_run_pushButton"));
        List_run_pushButton->setGeometry(QRect(240, 350, 101, 31));
        List_run_pushButton->setFont(font3);
        List_graph_pushButton = new QPushButton(centralWidget);
        List_graph_pushButton->setObjectName(QStringLiteral("List_graph_pushButton"));
        List_graph_pushButton->setGeometry(QRect(20, 350, 91, 31));
        List_csv_pushButton = new QPushButton(centralWidget);
        List_csv_pushButton->setObjectName(QStringLiteral("List_csv_pushButton"));
        List_csv_pushButton->setGeometry(QRect(130, 380, 91, 31));
        line_13 = new QFrame(centralWidget);
        line_13->setObjectName(QStringLiteral("line_13"));
        line_13->setGeometry(QRect(10, 255, 31, 16));
        line_13->setFrameShape(QFrame::HLine);
        line_13->setFrameShadow(QFrame::Sunken);
        line_14 = new QFrame(centralWidget);
        line_14->setObjectName(QStringLiteral("line_14"));
        line_14->setGeometry(QRect(80, 255, 271, 16));
        line_14->setFrameShape(QFrame::HLine);
        line_14->setFrameShadow(QFrame::Sunken);
        line_15 = new QFrame(centralWidget);
        line_15->setObjectName(QStringLiteral("line_15"));
        line_15->setGeometry(QRect(0, 263, 20, 151));
        line_15->setFrameShape(QFrame::VLine);
        line_15->setFrameShadow(QFrame::Sunken);
        line_16 = new QFrame(centralWidget);
        line_16->setObjectName(QStringLiteral("line_16"));
        line_16->setGeometry(QRect(340, 263, 20, 151));
        line_16->setFrameShape(QFrame::VLine);
        line_16->setFrameShadow(QFrame::Sunken);
        line_17 = new QFrame(centralWidget);
        line_17->setObjectName(QStringLiteral("line_17"));
        line_17->setGeometry(QRect(10, 405, 340, 20));
        line_17->setFrameShape(QFrame::HLine);
        line_17->setFrameShadow(QFrame::Sunken);
        line_18 = new QFrame(centralWidget);
        line_18->setObjectName(QStringLiteral("line_18"));
        line_18->setGeometry(QRect(10, 433, 31, 20));
        line_18->setFrameShape(QFrame::HLine);
        line_18->setFrameShadow(QFrame::Sunken);
        line_19 = new QFrame(centralWidget);
        line_19->setObjectName(QStringLiteral("line_19"));
        line_19->setGeometry(QRect(140, 433, 211, 20));
        line_19->setFrameShape(QFrame::HLine);
        line_19->setFrameShadow(QFrame::Sunken);
        CurrentLabel_3 = new QLabel(centralWidget);
        CurrentLabel_3->setObjectName(QStringLiteral("CurrentLabel_3"));
        CurrentLabel_3->setGeometry(QRect(40, 430, 121, 21));
        CurrentLabel_3->setFont(font);
        line_20 = new QFrame(centralWidget);
        line_20->setObjectName(QStringLiteral("line_20"));
        line_20->setGeometry(QRect(0, 443, 20, 131));
        line_20->setFrameShape(QFrame::VLine);
        line_20->setFrameShadow(QFrame::Sunken);
        Current_limitlabel_8 = new QLabel(centralWidget);
        Current_limitlabel_8->setObjectName(QStringLiteral("Current_limitlabel_8"));
        Current_limitlabel_8->setGeometry(QRect(20, 460, 71, 16));
        SW_frequency_lineEdit = new QLineEdit(centralWidget);
        SW_frequency_lineEdit->setObjectName(QStringLiteral("SW_frequency_lineEdit"));
        SW_frequency_lineEdit->setGeometry(QRect(20, 480, 81, 30));
        Current_limitlabel_9 = new QLabel(centralWidget);
        Current_limitlabel_9->setObjectName(QStringLiteral("Current_limitlabel_9"));
        Current_limitlabel_9->setGeometry(QRect(130, 460, 71, 16));
        SW_amplitude_lineEdit = new QLineEdit(centralWidget);
        SW_amplitude_lineEdit->setObjectName(QStringLiteral("SW_amplitude_lineEdit"));
        SW_amplitude_lineEdit->setGeometry(QRect(130, 480, 71, 30));
        Current_limitlabel_10 = new QLabel(centralWidget);
        Current_limitlabel_10->setObjectName(QStringLiteral("Current_limitlabel_10"));
        Current_limitlabel_10->setGeometry(QRect(105, 485, 21, 16));
        Current_limitlabel_10->setFont(font2);
        Current_limitlabel_11 = new QLabel(centralWidget);
        Current_limitlabel_11->setObjectName(QStringLiteral("Current_limitlabel_11"));
        Current_limitlabel_11->setGeometry(QRect(230, 460, 71, 16));
        SW_offset_lineEdit = new QLineEdit(centralWidget);
        SW_offset_lineEdit->setObjectName(QStringLiteral("SW_offset_lineEdit"));
        SW_offset_lineEdit->setGeometry(QRect(230, 480, 61, 30));
        Current_limitlabel_12 = new QLabel(centralWidget);
        Current_limitlabel_12->setObjectName(QStringLiteral("Current_limitlabel_12"));
        Current_limitlabel_12->setGeometry(QRect(205, 485, 21, 16));
        Current_limitlabel_12->setFont(font2);
        Current_limitlabel_13 = new QLabel(centralWidget);
        Current_limitlabel_13->setObjectName(QStringLiteral("Current_limitlabel_13"));
        Current_limitlabel_13->setGeometry(QRect(295, 485, 21, 16));
        Current_limitlabel_13->setFont(font2);
        SW_run_pushButton = new QPushButton(centralWidget);
        SW_run_pushButton->setObjectName(QStringLiteral("SW_run_pushButton"));
        SW_run_pushButton->setGeometry(QRect(240, 520, 101, 31));
        SW_run_pushButton->setFont(font3);
        line_21 = new QFrame(centralWidget);
        line_21->setObjectName(QStringLiteral("line_21"));
        line_21->setGeometry(QRect(340, 443, 20, 131));
        line_21->setFrameShape(QFrame::VLine);
        line_21->setFrameShadow(QFrame::Sunken);
        line_22 = new QFrame(centralWidget);
        line_22->setObjectName(QStringLiteral("line_22"));
        line_22->setGeometry(QRect(10, 565, 340, 20));
        line_22->setFrameShape(QFrame::HLine);
        line_22->setFrameShadow(QFrame::Sunken);
        Current_limitlabel_15 = new QLabel(centralWidget);
        Current_limitlabel_15->setObjectName(QStringLiteral("Current_limitlabel_15"));
        Current_limitlabel_15->setGeometry(QRect(200, 615, 41, 16));
        line_23 = new QFrame(centralWidget);
        line_23->setObjectName(QStringLiteral("line_23"));
        line_23->setGeometry(QRect(10, 590, 31, 20));
        line_23->setFrameShape(QFrame::HLine);
        line_23->setFrameShadow(QFrame::Sunken);
        R_current_lineEdit = new QLineEdit(centralWidget);
        R_current_lineEdit->setObjectName(QStringLiteral("R_current_lineEdit"));
        R_current_lineEdit->setGeometry(QRect(20, 630, 115, 30));
        R_RUN_pushButton = new QPushButton(centralWidget);
        R_RUN_pushButton->setObjectName(QStringLiteral("R_RUN_pushButton"));
        R_RUN_pushButton->setGeometry(QRect(250, 690, 91, 31));
        R_RUN_pushButton->setFont(font3);
        line_24 = new QFrame(centralWidget);
        line_24->setObjectName(QStringLiteral("line_24"));
        line_24->setGeometry(QRect(0, 600, 20, 161));
        line_24->setFrameShape(QFrame::VLine);
        line_24->setFrameShadow(QFrame::Sunken);
        line_25 = new QFrame(centralWidget);
        line_25->setObjectName(QStringLiteral("line_25"));
        line_25->setGeometry(QRect(10, 750, 340, 20));
        line_25->setFrameShape(QFrame::HLine);
        line_25->setFrameShadow(QFrame::Sunken);
        line_26 = new QFrame(centralWidget);
        line_26->setObjectName(QStringLiteral("line_26"));
        line_26->setGeometry(QRect(90, 590, 261, 20));
        line_26->setFrameShape(QFrame::HLine);
        line_26->setFrameShadow(QFrame::Sunken);
        CurrentLabel_4 = new QLabel(centralWidget);
        CurrentLabel_4->setObjectName(QStringLiteral("CurrentLabel_4"));
        CurrentLabel_4->setGeometry(QRect(40, 587, 181, 21));
        CurrentLabel_4->setFont(font);
        line_27 = new QFrame(centralWidget);
        line_27->setObjectName(QStringLiteral("line_27"));
        line_27->setGeometry(QRect(340, 600, 20, 161));
        line_27->setFrameShape(QFrame::VLine);
        line_27->setFrameShadow(QFrame::Sunken);
        ChannelLabel_2 = new QLabel(centralWidget);
        ChannelLabel_2->setObjectName(QStringLiteral("ChannelLabel_2"));
        ChannelLabel_2->setGeometry(QRect(480, 100, 151, 31));
        ChannelLabel_2->setFont(font4);
        SW_frequency_lineEdit_2 = new QLineEdit(centralWidget);
        SW_frequency_lineEdit_2->setObjectName(QStringLiteral("SW_frequency_lineEdit_2"));
        SW_frequency_lineEdit_2->setGeometry(QRect(390, 480, 81, 30));
        line_28 = new QFrame(centralWidget);
        line_28->setObjectName(QStringLiteral("line_28"));
        line_28->setGeometry(QRect(510, 433, 211, 20));
        line_28->setFrameShape(QFrame::HLine);
        line_28->setFrameShadow(QFrame::Sunken);
        Current_run_pushButton_2 = new QPushButton(centralWidget);
        Current_run_pushButton_2->setObjectName(QStringLiteral("Current_run_pushButton_2"));
        Current_run_pushButton_2->setGeometry(QRect(540, 170, 51, 31));
        Current_run_pushButton_2->setFont(font3);
        CurrentLabel_5 = new QLabel(centralWidget);
        CurrentLabel_5->setObjectName(QStringLiteral("CurrentLabel_5"));
        CurrentLabel_5->setGeometry(QRect(400, 140, 121, 21));
        CurrentLabel_5->setFont(font);
        line_29 = new QFrame(centralWidget);
        line_29->setObjectName(QStringLiteral("line_29"));
        line_29->setGeometry(QRect(710, 263, 20, 151));
        line_29->setFrameShape(QFrame::VLine);
        line_29->setFrameShadow(QFrame::Sunken);
        line_30 = new QFrame(centralWidget);
        line_30->setObjectName(QStringLiteral("line_30"));
        line_30->setGeometry(QRect(370, 263, 20, 151));
        line_30->setFrameShape(QFrame::VLine);
        line_30->setFrameShadow(QFrame::Sunken);
        Current_limitlabel_14 = new QLabel(centralWidget);
        Current_limitlabel_14->setObjectName(QStringLiteral("Current_limitlabel_14"));
        Current_limitlabel_14->setGeometry(QRect(500, 460, 71, 16));
        line_31 = new QFrame(centralWidget);
        line_31->setObjectName(QStringLiteral("line_31"));
        line_31->setGeometry(QRect(370, 153, 20, 86));
        line_31->setFrameShape(QFrame::VLine);
        line_31->setFrameShadow(QFrame::Sunken);
        List_csv_pushButton_2 = new QPushButton(centralWidget);
        List_csv_pushButton_2->setObjectName(QStringLiteral("List_csv_pushButton_2"));
        List_csv_pushButton_2->setGeometry(QRect(500, 380, 91, 31));
        line_32 = new QFrame(centralWidget);
        line_32->setObjectName(QStringLiteral("line_32"));
        line_32->setGeometry(QRect(380, 145, 21, 16));
        line_32->setFrameShape(QFrame::HLine);
        line_32->setFrameShadow(QFrame::Sunken);
        Current_limitlabel_16 = new QLabel(centralWidget);
        Current_limitlabel_16->setObjectName(QStringLiteral("Current_limitlabel_16"));
        Current_limitlabel_16->setGeometry(QRect(390, 460, 71, 16));
        List_run_pushButton_2 = new QPushButton(centralWidget);
        List_run_pushButton_2->setObjectName(QStringLiteral("List_run_pushButton_2"));
        List_run_pushButton_2->setGeometry(QRect(610, 350, 101, 31));
        List_run_pushButton_2->setFont(font3);
        List_current_lineEdit_2 = new QLineEdit(centralWidget);
        List_current_lineEdit_2->setObjectName(QStringLiteral("List_current_lineEdit_2"));
        List_current_lineEdit_2->setGeometry(QRect(390, 300, 115, 30));
        CurrentLabel_6 = new QLabel(centralWidget);
        CurrentLabel_6->setObjectName(QStringLiteral("CurrentLabel_6"));
        CurrentLabel_6->setGeometry(QRect(410, 250, 121, 21));
        CurrentLabel_6->setFont(font);
        Current_limitlabel_17 = new QLabel(centralWidget);
        Current_limitlabel_17->setObjectName(QStringLiteral("Current_limitlabel_17"));
        Current_limitlabel_17->setGeometry(QRect(600, 460, 71, 16));
        Current_limitlabel_18 = new QLabel(centralWidget);
        Current_limitlabel_18->setObjectName(QStringLiteral("Current_limitlabel_18"));
        Current_limitlabel_18->setGeometry(QRect(513, 305, 21, 16));
        Current_limitlabel_18->setFont(font2);
        SW_offset_lineEdit_2 = new QLineEdit(centralWidget);
        SW_offset_lineEdit_2->setObjectName(QStringLiteral("SW_offset_lineEdit_2"));
        SW_offset_lineEdit_2->setGeometry(QRect(600, 480, 61, 30));
        Current_limitlabel_19 = new QLabel(centralWidget);
        Current_limitlabel_19->setObjectName(QStringLiteral("Current_limitlabel_19"));
        Current_limitlabel_19->setGeometry(QRect(575, 485, 21, 16));
        Current_limitlabel_19->setFont(font2);
        line_36 = new QFrame(centralWidget);
        line_36->setObjectName(QStringLiteral("line_36"));
        line_36->setGeometry(QRect(710, 443, 20, 131));
        line_36->setFrameShape(QFrame::VLine);
        line_36->setFrameShadow(QFrame::Sunken);
        List_add_pushButton_2 = new QPushButton(centralWidget);
        List_add_pushButton_2->setObjectName(QStringLiteral("List_add_pushButton_2"));
        List_add_pushButton_2->setGeometry(QRect(680, 300, 31, 31));
        Current_limitlabel_20 = new QLabel(centralWidget);
        Current_limitlabel_20->setObjectName(QStringLiteral("Current_limitlabel_20"));
        Current_limitlabel_20->setGeometry(QRect(513, 175, 21, 16));
        Current_limitlabel_20->setFont(font2);
        line_37 = new QFrame(centralWidget);
        line_37->setObjectName(QStringLiteral("line_37"));
        line_37->setGeometry(QRect(370, 443, 20, 131));
        line_37->setFrameShape(QFrame::VLine);
        line_37->setFrameShadow(QFrame::Sunken);
        List_graph_pushButton_2 = new QPushButton(centralWidget);
        List_graph_pushButton_2->setObjectName(QStringLiteral("List_graph_pushButton_2"));
        List_graph_pushButton_2->setGeometry(QRect(390, 350, 91, 31));
        Current_limitlabel_21 = new QLabel(centralWidget);
        Current_limitlabel_21->setObjectName(QStringLiteral("Current_limitlabel_21"));
        Current_limitlabel_21->setGeometry(QRect(410, 200, 71, 16));
        line_39 = new QFrame(centralWidget);
        line_39->setObjectName(QStringLiteral("line_39"));
        line_39->setGeometry(QRect(710, 153, 20, 86));
        line_39->setFrameShape(QFrame::VLine);
        line_39->setFrameShadow(QFrame::Sunken);
        line_40 = new QFrame(centralWidget);
        line_40->setObjectName(QStringLiteral("line_40"));
        line_40->setGeometry(QRect(380, 433, 31, 20));
        line_40->setFrameShape(QFrame::HLine);
        line_40->setFrameShadow(QFrame::Sunken);
        List_time_lineEdit_2 = new QLineEdit(centralWidget);
        List_time_lineEdit_2->setObjectName(QStringLiteral("List_time_lineEdit_2"));
        List_time_lineEdit_2->setGeometry(QRect(530, 300, 115, 30));
        Current_limitlabel_22 = new QLabel(centralWidget);
        Current_limitlabel_22->setObjectName(QStringLiteral("Current_limitlabel_22"));
        Current_limitlabel_22->setGeometry(QRect(650, 305, 31, 21));
        Current_limitlabel_22->setFont(font2);
        SW_run_pushButton_2 = new QPushButton(centralWidget);
        SW_run_pushButton_2->setObjectName(QStringLiteral("SW_run_pushButton_2"));
        SW_run_pushButton_2->setGeometry(QRect(610, 520, 101, 31));
        SW_run_pushButton_2->setFont(font3);
        CurrentLabel_8 = new QLabel(centralWidget);
        CurrentLabel_8->setObjectName(QStringLiteral("CurrentLabel_8"));
        CurrentLabel_8->setGeometry(QRect(410, 430, 121, 21));
        CurrentLabel_8->setFont(font);
        Current_limitlabel_23 = new QLabel(centralWidget);
        Current_limitlabel_23->setObjectName(QStringLiteral("Current_limitlabel_23"));
        Current_limitlabel_23->setGeometry(QRect(420, 280, 61, 16));
        line_41 = new QFrame(centralWidget);
        line_41->setObjectName(QStringLiteral("line_41"));
        line_41->setGeometry(QRect(380, 405, 340, 20));
        line_41->setFrameShape(QFrame::HLine);
        line_41->setFrameShadow(QFrame::Sunken);
        List_clear_pushButton_2 = new QPushButton(centralWidget);
        List_clear_pushButton_2->setObjectName(QStringLiteral("List_clear_pushButton_2"));
        List_clear_pushButton_2->setGeometry(QRect(500, 350, 91, 31));
        Current_limitlabel_24 = new QLabel(centralWidget);
        Current_limitlabel_24->setObjectName(QStringLiteral("Current_limitlabel_24"));
        Current_limitlabel_24->setGeometry(QRect(665, 485, 21, 16));
        Current_limitlabel_24->setFont(font2);
        Current_limitlabel_25 = new QLabel(centralWidget);
        Current_limitlabel_25->setObjectName(QStringLiteral("Current_limitlabel_25"));
        Current_limitlabel_25->setGeometry(QRect(475, 485, 21, 16));
        Current_limitlabel_25->setFont(font2);
        SW_amplitude_lineEdit_2 = new QLineEdit(centralWidget);
        SW_amplitude_lineEdit_2->setObjectName(QStringLiteral("SW_amplitude_lineEdit_2"));
        SW_amplitude_lineEdit_2->setGeometry(QRect(500, 480, 71, 30));
        Current_lineEdit_2 = new QLineEdit(centralWidget);
        Current_lineEdit_2->setObjectName(QStringLiteral("Current_lineEdit_2"));
        Current_lineEdit_2->setGeometry(QRect(390, 170, 115, 30));
        line_42 = new QFrame(centralWidget);
        line_42->setObjectName(QStringLiteral("line_42"));
        line_42->setGeometry(QRect(520, 145, 201, 16));
        line_42->setFrameShape(QFrame::HLine);
        line_42->setFrameShadow(QFrame::Sunken);
        line_43 = new QFrame(centralWidget);
        line_43->setObjectName(QStringLiteral("line_43"));
        line_43->setGeometry(QRect(450, 255, 271, 16));
        line_43->setFrameShape(QFrame::HLine);
        line_43->setFrameShadow(QFrame::Sunken);
        line_44 = new QFrame(centralWidget);
        line_44->setObjectName(QStringLiteral("line_44"));
        line_44->setGeometry(QRect(380, 230, 340, 20));
        line_44->setFrameShape(QFrame::HLine);
        line_44->setFrameShadow(QFrame::Sunken);
        Current_limitlabel_27 = new QLabel(centralWidget);
        Current_limitlabel_27->setObjectName(QStringLiteral("Current_limitlabel_27"));
        Current_limitlabel_27->setGeometry(QRect(570, 280, 61, 16));
        line_46 = new QFrame(centralWidget);
        line_46->setObjectName(QStringLiteral("line_46"));
        line_46->setGeometry(QRect(380, 565, 340, 20));
        line_46->setFrameShape(QFrame::HLine);
        line_46->setFrameShadow(QFrame::Sunken);
        line_47 = new QFrame(centralWidget);
        line_47->setObjectName(QStringLiteral("line_47"));
        line_47->setGeometry(QRect(380, 255, 31, 16));
        line_47->setFrameShape(QFrame::HLine);
        line_47->setFrameShadow(QFrame::Sunken);
        Current_limitlabel_28 = new QLabel(centralWidget);
        Current_limitlabel_28->setObjectName(QStringLiteral("Current_limitlabel_28"));
        Current_limitlabel_28->setGeometry(QRect(410, 330, 71, 16));
        refresh_pushButton = new QPushButton(centralWidget);
        refresh_pushButton->setObjectName(QStringLiteral("refresh_pushButton"));
        refresh_pushButton->setGeometry(QRect(580, 50, 31, 21));
        QFont font5;
        font5.setFamily(QStringLiteral("Webdings"));
        font5.setPointSize(12);
        refresh_pushButton->setFont(font5);
        Current_limitlabel_29 = new QLabel(centralWidget);
        Current_limitlabel_29->setObjectName(QStringLiteral("Current_limitlabel_29"));
        Current_limitlabel_29->setGeometry(QRect(130, 510, 71, 16));
        Current_limitlabel_30 = new QLabel(centralWidget);
        Current_limitlabel_30->setObjectName(QStringLiteral("Current_limitlabel_30"));
        Current_limitlabel_30->setGeometry(QRect(500, 510, 71, 16));
        Current_limitlabel_31 = new QLabel(centralWidget);
        Current_limitlabel_31->setObjectName(QStringLiteral("Current_limitlabel_31"));
        Current_limitlabel_31->setGeometry(QRect(20, 510, 81, 16));
        Current_limitlabel_32 = new QLabel(centralWidget);
        Current_limitlabel_32->setObjectName(QStringLiteral("Current_limitlabel_32"));
        Current_limitlabel_32->setGeometry(QRect(390, 510, 81, 16));
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(410, 50, 51, 28));
        Current_stop_pushButton = new QPushButton(centralWidget);
        Current_stop_pushButton->setObjectName(QStringLiteral("Current_stop_pushButton"));
        Current_stop_pushButton->setGeometry(QRect(220, 170, 61, 31));
        Current_stop_pushButton->setFont(font3);
        Current_stop_pushButton_2 = new QPushButton(centralWidget);
        Current_stop_pushButton_2->setObjectName(QStringLiteral("Current_stop_pushButton_2"));
        Current_stop_pushButton_2->setGeometry(QRect(590, 170, 61, 31));
        Current_stop_pushButton_2->setFont(font3);
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(340, 10, 51, 61));
        label->setPixmap(QPixmap(QString::fromUtf8(":/resources/img/UACH.png")));
        label->setScaledContents(true);
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(190, 10, 141, 61));
        label_2->setPixmap(QPixmap(QString::fromUtf8(":/resources/img/janelia.png")));
        label_2->setScaledContents(true);
        Title_label_2 = new QLabel(centralWidget);
        Title_label_2->setObjectName(QStringLiteral("Title_label_2"));
        Title_label_2->setGeometry(QRect(30, 20, 101, 31));
        Title_label_2->setFont(font1);
        Title_label_3 = new QLabel(centralWidget);
        Title_label_3->setObjectName(QStringLiteral("Title_label_3"));
        Title_label_3->setGeometry(QRect(60, 40, 71, 31));
        Title_label_3->setFont(font1);
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(110, 0, 41, 41));
        label_3->setPixmap(QPixmap(QString::fromUtf8(":/resources/img/magnet.png")));
        label_3->setScaledContents(true);
        List_save_graph_pushButton = new QPushButton(centralWidget);
        List_save_graph_pushButton->setObjectName(QStringLiteral("List_save_graph_pushButton"));
        List_save_graph_pushButton->setGeometry(QRect(20, 380, 91, 31));
        R_time_lineEdit = new QLineEdit(centralWidget);
        R_time_lineEdit->setObjectName(QStringLiteral("R_time_lineEdit"));
        R_time_lineEdit->setGeometry(QRect(160, 630, 115, 30));
        Current_limitlabel_33 = new QLabel(centralWidget);
        Current_limitlabel_33->setObjectName(QStringLiteral("Current_limitlabel_33"));
        Current_limitlabel_33->setGeometry(QRect(141, 635, 21, 16));
        Current_limitlabel_33->setFont(font2);
        Current_limitlabel_34 = new QLabel(centralWidget);
        Current_limitlabel_34->setObjectName(QStringLiteral("Current_limitlabel_34"));
        Current_limitlabel_34->setGeometry(QRect(50, 615, 81, 16));
        Current_limitlabel_35 = new QLabel(centralWidget);
        Current_limitlabel_35->setObjectName(QStringLiteral("Current_limitlabel_35"));
        Current_limitlabel_35->setGeometry(QRect(280, 635, 31, 21));
        Current_limitlabel_35->setFont(font2);
        R_csv_pushButton = new QPushButton(centralWidget);
        R_csv_pushButton->setObjectName(QStringLiteral("R_csv_pushButton"));
        R_csv_pushButton->setGeometry(QRect(140, 720, 91, 31));
        R_clear_pushButton = new QPushButton(centralWidget);
        R_clear_pushButton->setObjectName(QStringLiteral("R_clear_pushButton"));
        R_clear_pushButton->setGeometry(QRect(140, 690, 91, 31));
        R_save_graph_pushButton = new QPushButton(centralWidget);
        R_save_graph_pushButton->setObjectName(QStringLiteral("R_save_graph_pushButton"));
        R_save_graph_pushButton->setGeometry(QRect(30, 720, 91, 31));
        R_graph_pushButton = new QPushButton(centralWidget);
        R_graph_pushButton->setObjectName(QStringLiteral("R_graph_pushButton"));
        R_graph_pushButton->setGeometry(QRect(30, 690, 91, 31));
        R_add_pushButton = new QPushButton(centralWidget);
        R_add_pushButton->setObjectName(QStringLiteral("R_add_pushButton"));
        R_add_pushButton->setGeometry(QRect(310, 630, 31, 31));
        line_34 = new QFrame(centralWidget);
        line_34->setObjectName(QStringLiteral("line_34"));
        line_34->setGeometry(QRect(460, 590, 261, 20));
        line_34->setFrameShape(QFrame::HLine);
        line_34->setFrameShadow(QFrame::Sunken);
        line_35 = new QFrame(centralWidget);
        line_35->setObjectName(QStringLiteral("line_35"));
        line_35->setGeometry(QRect(380, 590, 31, 20));
        line_35->setFrameShape(QFrame::HLine);
        line_35->setFrameShadow(QFrame::Sunken);
        R_graph_pushButton_2 = new QPushButton(centralWidget);
        R_graph_pushButton_2->setObjectName(QStringLiteral("R_graph_pushButton_2"));
        R_graph_pushButton_2->setGeometry(QRect(400, 690, 91, 31));
        CurrentLabel_7 = new QLabel(centralWidget);
        CurrentLabel_7->setObjectName(QStringLiteral("CurrentLabel_7"));
        CurrentLabel_7->setGeometry(QRect(410, 587, 181, 21));
        CurrentLabel_7->setFont(font);
        R_add_pushButton_2 = new QPushButton(centralWidget);
        R_add_pushButton_2->setObjectName(QStringLiteral("R_add_pushButton_2"));
        R_add_pushButton_2->setGeometry(QRect(680, 630, 31, 31));
        R_RUN_pushButton_2 = new QPushButton(centralWidget);
        R_RUN_pushButton_2->setObjectName(QStringLiteral("R_RUN_pushButton_2"));
        R_RUN_pushButton_2->setGeometry(QRect(620, 690, 91, 31));
        R_RUN_pushButton_2->setFont(font3);
        Current_limitlabel_36 = new QLabel(centralWidget);
        Current_limitlabel_36->setObjectName(QStringLiteral("Current_limitlabel_36"));
        Current_limitlabel_36->setGeometry(QRect(420, 615, 81, 16));
        Current_limitlabel_37 = new QLabel(centralWidget);
        Current_limitlabel_37->setObjectName(QStringLiteral("Current_limitlabel_37"));
        Current_limitlabel_37->setGeometry(QRect(511, 635, 21, 16));
        Current_limitlabel_37->setFont(font2);
        line_38 = new QFrame(centralWidget);
        line_38->setObjectName(QStringLiteral("line_38"));
        line_38->setGeometry(QRect(370, 600, 20, 161));
        line_38->setFrameShape(QFrame::VLine);
        line_38->setFrameShadow(QFrame::Sunken);
        R_clear_pushButton_2 = new QPushButton(centralWidget);
        R_clear_pushButton_2->setObjectName(QStringLiteral("R_clear_pushButton_2"));
        R_clear_pushButton_2->setGeometry(QRect(510, 690, 91, 31));
        R_csv_pushButton_2 = new QPushButton(centralWidget);
        R_csv_pushButton_2->setObjectName(QStringLiteral("R_csv_pushButton_2"));
        R_csv_pushButton_2->setGeometry(QRect(510, 720, 91, 31));
        R_time_lineEdit_2 = new QLineEdit(centralWidget);
        R_time_lineEdit_2->setObjectName(QStringLiteral("R_time_lineEdit_2"));
        R_time_lineEdit_2->setGeometry(QRect(530, 630, 115, 30));
        line_48 = new QFrame(centralWidget);
        line_48->setObjectName(QStringLiteral("line_48"));
        line_48->setGeometry(QRect(380, 750, 340, 20));
        line_48->setFrameShape(QFrame::HLine);
        line_48->setFrameShadow(QFrame::Sunken);
        R_current_lineEdit_2 = new QLineEdit(centralWidget);
        R_current_lineEdit_2->setObjectName(QStringLiteral("R_current_lineEdit_2"));
        R_current_lineEdit_2->setGeometry(QRect(390, 630, 115, 30));
        line_49 = new QFrame(centralWidget);
        line_49->setObjectName(QStringLiteral("line_49"));
        line_49->setGeometry(QRect(710, 600, 20, 161));
        line_49->setFrameShape(QFrame::VLine);
        line_49->setFrameShadow(QFrame::Sunken);
        Current_limitlabel_38 = new QLabel(centralWidget);
        Current_limitlabel_38->setObjectName(QStringLiteral("Current_limitlabel_38"));
        Current_limitlabel_38->setGeometry(QRect(650, 635, 31, 21));
        Current_limitlabel_38->setFont(font2);
        Current_limitlabel_26 = new QLabel(centralWidget);
        Current_limitlabel_26->setObjectName(QStringLiteral("Current_limitlabel_26"));
        Current_limitlabel_26->setGeometry(QRect(570, 615, 41, 16));
        R_save_graph_pushButton_2 = new QPushButton(centralWidget);
        R_save_graph_pushButton_2->setObjectName(QStringLiteral("R_save_graph_pushButton_2"));
        R_save_graph_pushButton_2->setGeometry(QRect(400, 720, 91, 31));
        List_save_graph_pushButton_2 = new QPushButton(centralWidget);
        List_save_graph_pushButton_2->setObjectName(QStringLiteral("List_save_graph_pushButton_2"));
        List_save_graph_pushButton_2->setGeometry(QRect(390, 380, 91, 31));
        Current_limitlabel_39 = new QLabel(centralWidget);
        Current_limitlabel_39->setObjectName(QStringLiteral("Current_limitlabel_39"));
        Current_limitlabel_39->setGeometry(QRect(40, 660, 71, 16));
        Current_limitlabel_40 = new QLabel(centralWidget);
        Current_limitlabel_40->setObjectName(QStringLiteral("Current_limitlabel_40"));
        Current_limitlabel_40->setGeometry(QRect(410, 660, 71, 16));
        checkBox_L1 = new QCheckBox(centralWidget);
        checkBox_L1->setObjectName(QStringLiteral("checkBox_L1"));
        checkBox_L1->setGeometry(QRect(240, 390, 91, 20));
        checkBox_SW1 = new QCheckBox(centralWidget);
        checkBox_SW1->setObjectName(QStringLiteral("checkBox_SW1"));
        checkBox_SW1->setGeometry(QRect(240, 550, 91, 20));
        checkBox_R1 = new QCheckBox(centralWidget);
        checkBox_R1->setObjectName(QStringLiteral("checkBox_R1"));
        checkBox_R1->setGeometry(QRect(250, 730, 91, 20));
        checkBox_L2 = new QCheckBox(centralWidget);
        checkBox_L2->setObjectName(QStringLiteral("checkBox_L2"));
        checkBox_L2->setGeometry(QRect(610, 390, 91, 20));
        checkBox_SW2 = new QCheckBox(centralWidget);
        checkBox_SW2->setObjectName(QStringLiteral("checkBox_SW2"));
        checkBox_SW2->setGeometry(QRect(610, 550, 91, 20));
        checkBox_R2 = new QCheckBox(centralWidget);
        checkBox_R2->setObjectName(QStringLiteral("checkBox_R2"));
        checkBox_R2->setGeometry(QRect(620, 730, 91, 20));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 738, 26));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Magnetic Tweezer Driver ", 0));
        SettingLabel->setText(QApplication::translate("MainWindow", "SETTINGS", 0));
        COMPORT_label->setText(QApplication::translate("MainWindow", "COM PORT", 0));
        Title_label->setText(QApplication::translate("MainWindow", "Magnetic", 0));
        Enable_pushButton->setText(QApplication::translate("MainWindow", "ENABLE", 0));
        CurrentLabel->setText(QApplication::translate("MainWindow", "CURRENT [A]", 0));
        Current_run_pushButton->setText(QApplication::translate("MainWindow", "RUN", 0));
        Current_limitlabel->setText(QApplication::translate("MainWindow", "(-1.0 to 1.0)", 0));
        ChannelLabel->setText(QApplication::translate("MainWindow", "CHANNEL 1", 0));
        CurrentLabel_2->setText(QApplication::translate("MainWindow", "LIST", 0));
        Current_limitlabel_2->setText(QApplication::translate("MainWindow", "(-1.0 to 1.0)", 0));
        Current_limitlabel_3->setText(QApplication::translate("MainWindow", "ms", 0));
        Current_limitlabel_4->setText(QApplication::translate("MainWindow", "A", 0));
        Current_limitlabel_5->setText(QApplication::translate("MainWindow", "A", 0));
        List_add_pushButton->setText(QApplication::translate("MainWindow", "+", 0));
        Current_limitlabel_6->setText(QApplication::translate("MainWindow", "CURRENT", 0));
        Current_limitlabel_7->setText(QApplication::translate("MainWindow", "TIME", 0));
        List_clear_pushButton->setText(QApplication::translate("MainWindow", "CLEAR ALL", 0));
        List_run_pushButton->setText(QApplication::translate("MainWindow", "RUN", 0));
        List_graph_pushButton->setText(QApplication::translate("MainWindow", "VIEW GRAPH", 0));
        List_csv_pushButton->setText(QApplication::translate("MainWindow", "EXPORT CSV", 0));
        CurrentLabel_3->setText(QApplication::translate("MainWindow", "SINE WAVE", 0));
        Current_limitlabel_8->setText(QApplication::translate("MainWindow", "FREQUENCY", 0));
        Current_limitlabel_9->setText(QApplication::translate("MainWindow", "AMPLITUDE", 0));
        Current_limitlabel_10->setText(QApplication::translate("MainWindow", "Hz", 0));
        Current_limitlabel_11->setText(QApplication::translate("MainWindow", "OFFSET", 0));
        Current_limitlabel_12->setText(QApplication::translate("MainWindow", "A", 0));
        Current_limitlabel_13->setText(QApplication::translate("MainWindow", "A", 0));
        SW_run_pushButton->setText(QApplication::translate("MainWindow", "RUN", 0));
        Current_limitlabel_15->setText(QApplication::translate("MainWindow", "TIME", 0));
        R_RUN_pushButton->setText(QApplication::translate("MainWindow", "RUN", 0));
        CurrentLabel_4->setText(QApplication::translate("MainWindow", "RAMP", 0));
        ChannelLabel_2->setText(QApplication::translate("MainWindow", "CHANNEL 2", 0));
        Current_run_pushButton_2->setText(QApplication::translate("MainWindow", "RUN", 0));
        CurrentLabel_5->setText(QApplication::translate("MainWindow", "CURRENT [A]", 0));
        Current_limitlabel_14->setText(QApplication::translate("MainWindow", "AMPLITUDE", 0));
        List_csv_pushButton_2->setText(QApplication::translate("MainWindow", "EXPORT CSV", 0));
        Current_limitlabel_16->setText(QApplication::translate("MainWindow", "FREQUENCY", 0));
        List_run_pushButton_2->setText(QApplication::translate("MainWindow", "RUN", 0));
        CurrentLabel_6->setText(QApplication::translate("MainWindow", "LIST", 0));
        Current_limitlabel_17->setText(QApplication::translate("MainWindow", "OFFSET", 0));
        Current_limitlabel_18->setText(QApplication::translate("MainWindow", "A", 0));
        Current_limitlabel_19->setText(QApplication::translate("MainWindow", "A", 0));
        List_add_pushButton_2->setText(QApplication::translate("MainWindow", "+", 0));
        Current_limitlabel_20->setText(QApplication::translate("MainWindow", "A", 0));
        List_graph_pushButton_2->setText(QApplication::translate("MainWindow", "VIEW GRAPH", 0));
        Current_limitlabel_21->setText(QApplication::translate("MainWindow", "(-1.0 to 1.0)", 0));
        Current_limitlabel_22->setText(QApplication::translate("MainWindow", "ms", 0));
        SW_run_pushButton_2->setText(QApplication::translate("MainWindow", "RUN", 0));
        CurrentLabel_8->setText(QApplication::translate("MainWindow", "SINE WAVE", 0));
        Current_limitlabel_23->setText(QApplication::translate("MainWindow", "CURRENT", 0));
        List_clear_pushButton_2->setText(QApplication::translate("MainWindow", "CLEAR ALL", 0));
        Current_limitlabel_24->setText(QApplication::translate("MainWindow", "A", 0));
        Current_limitlabel_25->setText(QApplication::translate("MainWindow", "Hz", 0));
        Current_limitlabel_27->setText(QApplication::translate("MainWindow", "TIME", 0));
        Current_limitlabel_28->setText(QApplication::translate("MainWindow", "(-1.0 to 1.0)", 0));
        refresh_pushButton->setText(QApplication::translate("MainWindow", "\357\201\261", 0));
        Current_limitlabel_29->setText(QApplication::translate("MainWindow", "(-1.0 to 1.0)", 0));
        Current_limitlabel_30->setText(QApplication::translate("MainWindow", "(-1.0 to 1.0)", 0));
        Current_limitlabel_31->setText(QApplication::translate("MainWindow", "(0.1 to 100.0)", 0));
        Current_limitlabel_32->setText(QApplication::translate("MainWindow", "(0.1 to 100.0)", 0));
        pushButton->setText(QApplication::translate("MainWindow", "About", 0));
        Current_stop_pushButton->setText(QApplication::translate("MainWindow", "STOP", 0));
        Current_stop_pushButton_2->setText(QApplication::translate("MainWindow", "STOP", 0));
        label->setText(QString());
        label_2->setText(QString());
        Title_label_2->setText(QApplication::translate("MainWindow", "Tweezer", 0));
        Title_label_3->setText(QApplication::translate("MainWindow", "Driver", 0));
        label_3->setText(QString());
        List_save_graph_pushButton->setText(QApplication::translate("MainWindow", "SAVE GRAPH", 0));
        Current_limitlabel_33->setText(QApplication::translate("MainWindow", "A", 0));
        Current_limitlabel_34->setText(QApplication::translate("MainWindow", "CURRENT", 0));
        Current_limitlabel_35->setText(QApplication::translate("MainWindow", "ms", 0));
        R_csv_pushButton->setText(QApplication::translate("MainWindow", "EXPORT CSV", 0));
        R_clear_pushButton->setText(QApplication::translate("MainWindow", "CLEAR ALL", 0));
        R_save_graph_pushButton->setText(QApplication::translate("MainWindow", "SAVE GRAPH", 0));
        R_graph_pushButton->setText(QApplication::translate("MainWindow", "VIEW GRAPH", 0));
        R_add_pushButton->setText(QApplication::translate("MainWindow", "+", 0));
        R_graph_pushButton_2->setText(QApplication::translate("MainWindow", "VIEW GRAPH", 0));
        CurrentLabel_7->setText(QApplication::translate("MainWindow", "RAMP", 0));
        R_add_pushButton_2->setText(QApplication::translate("MainWindow", "+", 0));
        R_RUN_pushButton_2->setText(QApplication::translate("MainWindow", "RUN", 0));
        Current_limitlabel_36->setText(QApplication::translate("MainWindow", "CURRENT", 0));
        Current_limitlabel_37->setText(QApplication::translate("MainWindow", "A", 0));
        R_clear_pushButton_2->setText(QApplication::translate("MainWindow", "CLEAR ALL", 0));
        R_csv_pushButton_2->setText(QApplication::translate("MainWindow", "EXPORT CSV", 0));
        Current_limitlabel_38->setText(QApplication::translate("MainWindow", "ms", 0));
        Current_limitlabel_26->setText(QApplication::translate("MainWindow", "TIME", 0));
        R_save_graph_pushButton_2->setText(QApplication::translate("MainWindow", "SAVE GRAPH", 0));
        List_save_graph_pushButton_2->setText(QApplication::translate("MainWindow", "SAVE GRAPH", 0));
        Current_limitlabel_39->setText(QApplication::translate("MainWindow", "(-1.0 to 1.0)", 0));
        Current_limitlabel_40->setText(QApplication::translate("MainWindow", "(-1.0 to 1.0)", 0));
        checkBox_L1->setText(QApplication::translate("MainWindow", "TTL Trigger?", 0));
        checkBox_SW1->setText(QApplication::translate("MainWindow", "TTL Trigger?", 0));
        checkBox_R1->setText(QApplication::translate("MainWindow", "TTL Trigger?", 0));
        checkBox_L2->setText(QApplication::translate("MainWindow", "TTL Trigger?", 0));
        checkBox_SW2->setText(QApplication::translate("MainWindow", "TTL Trigger?", 0));
        checkBox_R2->setText(QApplication::translate("MainWindow", "TTL Trigger?", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
